### ISSUE TITLE
Dockerfile 오류

### ISSUE THREAD

**Issue by tigrison** [TigerCompany-tigris/tigris-user-service#7]
Dockerfile(tigris-user-service/mecab/server/Dockerfile)

36라인 RUN pip3 instal -U pip setuptools 오타입니다 > RUN pip3 install -U pip setuptools

39라인 COPY test.txt . 해당 파일이 존재하지 않습니다.

테스트를 위해 36라인 오타 수정 및 39라인 제거를 하여 임의 반영했습니다

**Comment by hephaex** [comment]
fixed commit da174fc3
 - RUN pip3 install -U pip setuptools
 - delete COPY test.txt .
